# Generated by Django 5.1.5 on 2025-02-12 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_mapname_remove_choice_votes_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Option Name')),
                ('onmaps', models.BooleanField(verbose_name='Included In Map Page?')),
                ('onbuildings', models.BooleanField(verbose_name='Included In Building Page?')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('map_color', models.CharField(default='000000', max_length=6, verbose_name='Map Color')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floors', models.IntegerField(default=1)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('on_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.map')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Mapname',
        ),
    ]
