# Generated by Django 5.1.5 on 2025-02-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_rename_filters_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
