# Generated by Django 5.1.5 on 2025-02-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_building_display_name_map_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='map',
            name='center',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='map',
            name='map_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='map',
            name='zoom',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
