# Generated by Django 5.1.6 on 2025-02-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_building_display_name_map_display_name_and_more'),
        ('directory', '0005_locations'),
    ]

    operations = [
    ]
