# Generated by Django 5.1.6 on 2025-02-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_merge_20250224_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='center',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='map',
            name='map_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='map',
            name='zoom',
            field=models.IntegerField(default=17),
        ),
    ]
