# Generated by Django 5.1.5 on 2025-02-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_filter_display_name_map_center_map_map_id_map_zoom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('coordinates', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='filter',
            name='onbuildings',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='onmaps',
        ),
        migrations.AddField(
            model_name='map',
            name='filters',
            field=models.ManyToManyField(blank=True, to='directory.filter'),
        ),
        migrations.AddField(
            model_name='filter',
            name='locations',
            field=models.ManyToManyField(blank=True, to='directory.location'),
        ),
    ]
