# Generated by Django 5.1.6 on 2025-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_map_center_map_map_id_map_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
