# Generated by Django 5.1.5 on 2025-03-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_location_remove_filter_onbuildings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_color',
        ),
    ]
