# Generated by Django 5.1.6 on 2025-02-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_location_delete_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='filter_category',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
