# Generated by Django 5.1.6 on 2025-03-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_location_coordinates_location_filter_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
