# Generated by Django 5.1.6 on 2025-03-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_location_remove_filter_onbuildings_and_more'),
        ('directory', '0010_rename_coordinates_location_latitude_and_more'),
    ]

    operations = [
    ]
