# Generated by Django 5.1.5 on 2025-03-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_remove_filter_locations_remove_map_map_color'),
        ('directory', '0011_merge_20250303_1831'),
    ]

    operations = [
    ]
