# Generated by Django 5.1.5 on 2025-03-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_merge_20250304_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='coordinates',
            new_name='filter_category',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='filters',
        ),
        migrations.AddField(
            model_name='filter',
            name='onbuildings',
            field=models.BooleanField(null=True, verbose_name='Included In Building Page?'),
        ),
        migrations.AddField(
            model_name='filter',
            name='onmaps',
            field=models.BooleanField(null=True, verbose_name='Included In Map Page?'),
        ),
        migrations.AddField(
            model_name='location',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Option Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
