# Generated by Django 5.1.5 on 2025-03-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_remove_filter_display_name_remove_filter_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='filter_category',
        ),
    ]
