# Generated by Django 5.1.5 on 2025-03-04 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_rename_coordinates_location_filter_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='onbuildings',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='onmaps',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingSearchBox/'),
        ),
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_type',
            field=models.CharField(choices=[('Map', 'Map'), ('Building', 'Building')], default='Map', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='on_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.building'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.filter'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
