# Generated by Django 5.1.5 on 2025-03-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_remove_location_filter_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='onbuildings',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='onmaps',
        ),
    ]
