# Generated by Django 5.1.5 on 2025-03-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_remove_filter_onbuildings_remove_filter_onmaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_type',
            field=models.CharField(choices=[('Map', 'Map'), ('Building', 'Building')], default='Map', max_length=100),
        ),
    ]
