# Generated by Django 5.1.5 on 2025-03-05 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_filter_display_name_filter_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='filter_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.filter'),
        ),
        migrations.AddField(
            model_name='location',
            name='on_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.building'),
        ),
    ]
