# Generated by Django 5.1.5 on 2025-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_location_filter_category_location_on_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='floor_plan',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_five',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_four',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_one',
            field=models.ImageField(null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_three',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_two',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='ground_floor',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='sidebar_image',
            field=models.ImageField(null=True, upload_to='images/buildingSearchBox/'),
        ),
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
