# Generated by Django 5.1.5 on 2025-03-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_remove_building_floor_plan_building_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
    ]
