# Generated by Django 5.1.5 on 2025-04-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0018_remove_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='has_ground_floor',
            field=models.BooleanField(default=False),
        ),
    ]
