# Generated by Django 5.1.5 on 2025-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_building_has_ground_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='floor_one',
            new_name='floor_1',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='floor_five',
            new_name='floor_2',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='floor_four',
            new_name='floor_3',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='floor_three',
            new_name='floor_4',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='floor_two',
            new_name='floor_5',
        ),
    ]
