# Generated by Django 5.1.5 on 2025-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_rename_floor_one_building_floor_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='floor_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
        migrations.AddField(
            model_name='building',
            name='floor_7',
            field=models.ImageField(blank=True, null=True, upload_to='images/buildingFloors'),
        ),
    ]
