# Generated by Django 5.1.5 on 2025-04-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_alter_building_options'),
        ('directory', '0021_building_floor_6_building_floor_7'),
    ]

    operations = [
    ]
