# Generated by Django 5.1.7 on 2025-04-11 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_merge_20250410_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('x_coord', models.FloatField(help_text='X coordinate as percentage (0–100)')),
                ('y_coord', models.FloatField(help_text='Y coordinate as percentage (0–100)')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.building')),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.filter')),
            ],
        ),
    ]
