# Generated by Django 5.1.7 on 2025-04-11 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_poicategory_remove_poi_filter_category_poi_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/POI_Icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='poi',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.poifilter'),
        ),
        migrations.DeleteModel(
            name='POICategory',
        ),
    ]
