# Generated by Django 5.1.7 on 2025-04-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_poifilter_alter_poi_category_delete_poicategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFloorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/floorCategoryPlans/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.building')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.poifilter')),
            ],
        ),
        migrations.DeleteModel(
            name='POI',
        ),
    ]
