# Generated by Django 5.1.7 on 2025-04-11 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0026_categoryfloorimage_delete_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poifilter',
            name='icon',
        ),
        migrations.CreateModel(
            name='BuildingCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/buildingCategoryImages/')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.building')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.poifilter')),
            ],
            options={
                'ordering': ['building__display_name', 'floor', 'category__name'],
            },
        ),
        migrations.DeleteModel(
            name='CategoryFloorImage',
        ),
    ]
