# Generated by Django 5.1.7 on 2025-04-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_remove_poifilter_icon_buildingcategoryimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='adress',
            new_name='address',
        ),
    ]
