# Generated by Django 5.1.7 on 2025-04-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_rename_adress_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcategoryimage',
            name='is_ground_floor',
            field=models.BooleanField(default=False),
        ),
    ]
